config: add CONFIG_INET_DIAG_DESTROY=y
Fix: junit.framework.ComparisonFailure:
expected:<[Software caused connection abor]t> but was:<[Read timed ou]t>
CTS failures

Bug: 34035473
Change-Id: Ifb30992b09df7522af275e15efb326b1c4b10451
Signed-off-by: Ben Fennema <fennema@google.com>